### ISSUE TITLE
Determine whether to put `rust-test` back in CI Workflow

### ISSUE THREAD

**Issue by ALRubinger** [TBD54566975/tbdex-rs#104]
I removed this section as part of #94:

```
  rust-test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Init Hermit
        uses: cashapp/activate-hermit@v1
        with:
          cache: true
      - name: Setup
        run: just setup
      - name: Install Nextest
        run: cargo install cargo-nextest
      - name: Create nextest.toml
        run: |
          echo '[profile.ci.junit]' > nextest.toml
          echo 'path = "junit.xml"' >> nextest.toml
          echo 'store-success-output = true' >> nextest.toml
          echo 'store-failure-output = true' >> nextest.toml
      - name: Run Rust Tests
        run: |
          mkdir -p test-results
          cargo nextest run --profile ci --config-file ./nextest.toml
      - name: Modify testsuite name in XML for test runner consumption
        run: |
          sed -i '' 's/<testsuite name="tbdex"/<testsuite name="TbdexTestVectorsProtocolTest"/' target/nextest/ci/junit.xml
      - name: Move Test Results
        run: mv target/nextest/ci/junit.xml test-results/rust-test-results.xml
      - name: Upload Rust Test Results
        uses: actions/upload-artifact@v3
        with:
          name: rust-test-results
          path: test-results/rust-test-results.xml
```

Determine whether we should put it back :)
